# Site settings
title: Chao Chen
# general_email: kandy.cs@gmail.com
academic_email: chao.chen@gatech.edu

description: > # this means to ignore newlines until "baseurl:" Give a brief description of yourself, and maybe your passion/interests. It is displayed in search results.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://cchen435.com" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: kandycs
linkedin_username: kandycs
googlescholar: https://scholar.google.com/citations?user=34_6IksAAAAJ&hl=en
# facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title